-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 6.5
--C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n ROM -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type bram -wp 10 -rp 0011 -rdata_width 8 -data_width 8 -num_rows 3072 -cascade 11 -memfile c:/kevan/a3041/p3041/rom.mem -memformat hex 

-- Tue Aug 29 10:28:28 2023

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity ROM is
    port (
        WrAddress: in  std_logic_vector(11 downto 0); 
        RdAddress: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        WE: in  std_logic; 
        RdClock: in  std_logic; 
        RdClockEn: in  std_logic; 
        Reset: in  std_logic; 
        WrClock: in  std_logic; 
        WrClockEn: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0));
end ROM;

architecture Structure of ROM is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal raddr10_ff: std_logic;
    signal scuba_vlo: std_logic;
    signal mdout1_0_0_2: std_logic;
    signal mdout1_0_0: std_logic;
    signal mdout1_0_1_2: std_logic;
    signal mdout1_0_1: std_logic;
    signal mdout1_0_2_2: std_logic;
    signal mdout1_0_2: std_logic;
    signal mdout1_0_3_2: std_logic;
    signal mdout1_0_3: std_logic;
    signal mdout1_0_4: std_logic;
    signal mdout1_0_0_1: std_logic;
    signal mdout1_0_5: std_logic;
    signal mdout1_0_1_1: std_logic;
    signal mdout1_0_6: std_logic;
    signal mdout1_0_2_1: std_logic;
    signal raddr11_ff: std_logic;
    signal mdout1_0_7: std_logic;
    signal mdout1_0_3_1: std_logic;

    -- local component declarations
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component MUX21
        port (D0: in  std_logic; D1: in  std_logic; SD: in  std_logic; 
            Z: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component DP8KC
        generic (INIT_DATA : in String; INITVAL_1F : in String; 
                INITVAL_1E : in String; INITVAL_1D : in String; 
                INITVAL_1C : in String; INITVAL_1B : in String; 
                INITVAL_1A : in String; INITVAL_19 : in String; 
                INITVAL_18 : in String; INITVAL_17 : in String; 
                INITVAL_16 : in String; INITVAL_15 : in String; 
                INITVAL_14 : in String; INITVAL_13 : in String; 
                INITVAL_12 : in String; INITVAL_11 : in String; 
                INITVAL_10 : in String; INITVAL_0F : in String; 
                INITVAL_0E : in String; INITVAL_0D : in String; 
                INITVAL_0C : in String; INITVAL_0B : in String; 
                INITVAL_0A : in String; INITVAL_09 : in String; 
                INITVAL_08 : in String; INITVAL_07 : in String; 
                INITVAL_06 : in String; INITVAL_05 : in String; 
                INITVAL_04 : in String; INITVAL_03 : in String; 
                INITVAL_02 : in String; INITVAL_01 : in String; 
                INITVAL_00 : in String; ASYNC_RESET_RELEASE : in String; 
                RESETMODE : in String; GSR : in String; 
                WRITEMODE_B : in String; WRITEMODE_A : in String; 
                CSDECODE_B : in String; CSDECODE_A : in String; 
                REGMODE_B : in String; REGMODE_A : in String; 
                DATA_WIDTH_B : in Integer; DATA_WIDTH_A : in Integer);
        port (DIA8: in  std_logic; DIA7: in  std_logic; 
            DIA6: in  std_logic; DIA5: in  std_logic; 
            DIA4: in  std_logic; DIA3: in  std_logic; 
            DIA2: in  std_logic; DIA1: in  std_logic; 
            DIA0: in  std_logic; ADA12: in  std_logic; 
            ADA11: in  std_logic; ADA10: in  std_logic; 
            ADA9: in  std_logic; ADA8: in  std_logic; 
            ADA7: in  std_logic; ADA6: in  std_logic; 
            ADA5: in  std_logic; ADA4: in  std_logic; 
            ADA3: in  std_logic; ADA2: in  std_logic; 
            ADA1: in  std_logic; ADA0: in  std_logic; CEA: in  std_logic; 
            OCEA: in  std_logic; CLKA: in  std_logic; WEA: in  std_logic; 
            CSA2: in  std_logic; CSA1: in  std_logic; 
            CSA0: in  std_logic; RSTA: in  std_logic; 
            DIB8: in  std_logic; DIB7: in  std_logic; 
            DIB6: in  std_logic; DIB5: in  std_logic; 
            DIB4: in  std_logic; DIB3: in  std_logic; 
            DIB2: in  std_logic; DIB1: in  std_logic; 
            DIB0: in  std_logic; ADB12: in  std_logic; 
            ADB11: in  std_logic; ADB10: in  std_logic; 
            ADB9: in  std_logic; ADB8: in  std_logic; 
            ADB7: in  std_logic; ADB6: in  std_logic; 
            ADB5: in  std_logic; ADB4: in  std_logic; 
            ADB3: in  std_logic; ADB2: in  std_logic; 
            ADB1: in  std_logic; ADB0: in  std_logic; CEB: in  std_logic; 
            OCEB: in  std_logic; CLKB: in  std_logic; WEB: in  std_logic; 
            CSB2: in  std_logic; CSB1: in  std_logic; 
            CSB0: in  std_logic; RSTB: in  std_logic; 
            DOA8: out  std_logic; DOA7: out  std_logic; 
            DOA6: out  std_logic; DOA5: out  std_logic; 
            DOA4: out  std_logic; DOA3: out  std_logic; 
            DOA2: out  std_logic; DOA1: out  std_logic; 
            DOA0: out  std_logic; DOB8: out  std_logic; 
            DOB7: out  std_logic; DOB6: out  std_logic; 
            DOB5: out  std_logic; DOB4: out  std_logic; 
            DOB3: out  std_logic; DOB2: out  std_logic; 
            DOB1: out  std_logic; DOB0: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of ROM_0_0_0_2 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_0_0_0_2 : label is "rom.mem";
    attribute MEM_LPC_FILE of ROM_0_0_1_1 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_0_0_1_1 : label is "rom.mem";
    attribute MEM_LPC_FILE of ROM_1_0_0_0 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_1_0_0_0 : label is "rom.mem";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    ROM_0_0_0_2: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x000000000000000000000000000000000000000000000000000EA1510A000EA20032040EA2002004", 
        INITVAL_17=> "0x1A8800C2900AE85000380BA13108D508C0500E6008E0502A70082050000606211008060621900822", 
        INITVAL_16=> "0x104530222808685000480BE03010000B4840205100AB8080C5140800AC8500085042980001010000", 
        INITVAL_15=> "0x03603074701B05010A00024340AC500A00A00A1014A1A00A000A05100405008300A005024410C082", 
        INITVAL_14=> "0x00404026400A004024510C08200204026410C08200004060100204F090200A073008100AC4008201", 
        INITVAL_13=> "0x008000A850082020080506018008C00A2041A05200865086210105D10A101C07A0E0000A85A08800", 
        INITVAL_12=> "0x08205142040005E000400F4701B05010A00024340AC8510A580A2030640102043064010004508211", 
        INITVAL_11=> "0x112800AC1111254050560A81208411030A912C0C0420508601022890C218120420EA650821111210", 
        INITVAL_10=> "0x0AC111129404C560A81B050111124404A560A8180501111244048560A81103011112B00AC1111244", 
        INITVAL_0F=> "0x046560A81310AE107045082300A06200A051FE3310A130704106601022890D05000A610309C06425", 
        INITVAL_0E=> "0x0CA4107052066840F050020500B4051C05F00A000A00100A600B20502011112800AC11112700AC11", 
        INITVAL_0D=> "0x112600AC11112500AC11112400AC11112300AC11112200AC11112100AC11112000AC11112F304256", 
        INITVAL_0C=> "0x0A81310AD10704610A900A00103090064050CA421EA030A82F0A043062530480302A530480402C11", 
        INITVAL_0B=> "0x112400C218126060C0B808A0A1080402A45000500E684020520A88410C540641010AD80A2001CEA7", 
        INITVAL_0A=> "0x00A67040B80A20810A03198CC1704A10AF31704910AA808EF01705000EF017052012240A00700A60", 
        INITVAL_09=> "0x02A060E206016840A0A808C500F4700E40B10A1011052078CC182041505F06204130501087E00285", 
        INITVAL_08=> "0x0FC0110A7F016850007F016850400714E07040B80A20810A13198CC0204910AB0094851E61008EF0", 
        INITVAL_07=> "0x1705000EF0170520007A0E0100A005000E10800500E000820502A100807B00ED80A085000180BC11", 
        INITVAL_06=> "0x108560005001814040500E404060510A6041821300A06040500BEF308230032041705101085002CC", 
        INITVAL_05=> "0x180040E21810A0018220034040E21810A0018220032041305001485020401101106218008480A20C", 
        INITVAL_04=> "0x026110504A00A100A05001214040500E404060500E604080510A8041223002A041221A00A680A009", 
        INITVAL_03=> "0x028C00A07C008D00A25D008680A00418230034041C0521C041006041E0521E041008040005000041", 
        INITVAL_02=> "0x00A0402051000041C0500FC041E0500FE04000510A0040305D022850461808885040910641210865", 
        INITVAL_01=> "0x03051062840E0851B051000A7002200DA85000851D04D10A101F050022101E0D80A085000100F470", 
        INITVAL_00=> "0x06A620C255002501005601806120330A00300A6000068008201802600A000060800C5300EE003651", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(3), 
            DIA2=>Data(2), DIA1=>Data(1), DIA0=>Data(0), 
            ADA12=>WrAddress(10), ADA11=>WrAddress(9), 
            ADA10=>WrAddress(8), ADA9=>WrAddress(7), ADA8=>WrAddress(6), 
            ADA7=>WrAddress(5), ADA6=>WrAddress(4), ADA5=>WrAddress(3), 
            ADA4=>WrAddress(2), ADA3=>WrAddress(1), ADA2=>WrAddress(0), 
            ADA1=>scuba_vlo, ADA0=>scuba_vlo, CEA=>WrClockEn, 
            OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>WrAddress(11), RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>RdAddress(10), ADB11=>RdAddress(9), 
            ADB10=>RdAddress(8), ADB9=>RdAddress(7), ADB8=>RdAddress(6), 
            ADB7=>RdAddress(5), ADB6=>RdAddress(4), ADB5=>RdAddress(3), 
            ADB4=>RdAddress(2), ADB3=>RdAddress(1), ADB2=>RdAddress(0), 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>RdAddress(11), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>mdout1_0_3, DOB2=>mdout1_0_2, DOB1=>mdout1_0_1, 
            DOB0=>mdout1_0_0);

    ROM_0_0_1_1: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000160000020116000080011600008801", 
        INITVAL_17=> "0x1800000000022010020003E70002F0000010080002001008000220100200000710020000070002C0", 
        INITVAL_16=> "0x0180000E10020010020003E14000300220106014002100200100240020010028000C510023204200", 
        INITVAL_15=> "0x02200020330001100201066330661002010002010C00000201020100220106410028320643200003", 
        INITVAL_14=> "0x04A010641002832064320000304A01064320000304A01064320601A0005002040002500280002620", 
        INITVAL_13=> "0x00250028000262000260000400020002001000100022204422020100020100420066300367C00030", 
        INITVAL_12=> "0x026010E60106017060120403300011002010663306631002000201200004040120000404018000D0", 
        INITVAL_11=> "0x00A40022D000A9000041100060006D000550220002628000041A00503A000AE0000818000D000A40", 
        INITVAL_10=> "0x022D000A400004110006000D000A300004110002000D000A20000411000F000D000A00022D000A10", 
        INITVAL_0F=> "0x0004110000002F7000180004002624002321EE10002070001F000041A005020140021D0005F00004", 
        INITVAL_0E=> "0x03000000100E0010201604210020010001000210020110021002001002D000A00022D000A00022D0", 
        INITVAL_0D=> "0x00A00022D000A00022D000A00022D000A00022D000A00022D000A00022D000A00022D000AB000041", 
        INITVAL_0C=> "0x10000002F700010002000201D0005400004032001E8321200F0862200010008320641000832064D0", 
        INITVAL_0B=> "0x00A3203A000A62106410026210020003200040100820104010082010442204421002000201200403", 
        INITVAL_0A=> "0x066360620002010002070EE770201000207020100021002CF10001002CF10001002E000640406432", 
        INITVAL_09=> "0x008320C413042010641002422040330C61000201000100EE770E801000100E801000100026102001", 
        INITVAL_08=> "0x0C2100026F020010026F0200100222006360620002010002070EE7708010002000200100E4002CF1", 
        INITVAL_07=> "0x0001002CF100010024200662002401002E0004010082002401008200242006600022010021003E71", 
        INITVAL_06=> "0x0023308010036000801008801080100880116004002320801305E71140000800100010020010C877", 
        INITVAL_05=> "0x0E00110000002610E0000800110000002210C000080010001002001080100005000074002000201B", 
        INITVAL_04=> "0x00007000100020102010026000201008201020100820102012082010600008201060000020002013", 
        INITVAL_03=> "0x00000020400020002440002000200100000080010001400013040010001400013040010201402013", 
        INITVAL_02=> "0x040010201003C000001008001000100800102012082010201F0E20100E1002001002300007000222", 
        INITVAL_01=> "0x020100E20104201000100240306650000010024400010002010001304C3200200022010022204033", 
        INITVAL_00=> "0x0663304621000320E62304E3206006064040643208622000320E6230462002620024220446000E00", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(7), 
            DIA2=>Data(6), DIA1=>Data(5), DIA0=>Data(4), 
            ADA12=>WrAddress(10), ADA11=>WrAddress(9), 
            ADA10=>WrAddress(8), ADA9=>WrAddress(7), ADA8=>WrAddress(6), 
            ADA7=>WrAddress(5), ADA6=>WrAddress(4), ADA5=>WrAddress(3), 
            ADA4=>WrAddress(2), ADA3=>WrAddress(1), ADA2=>WrAddress(0), 
            ADA1=>scuba_vlo, ADA0=>scuba_vlo, CEA=>WrClockEn, 
            OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>WrAddress(11), RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>RdAddress(10), ADB11=>RdAddress(9), 
            ADB10=>RdAddress(8), ADB9=>RdAddress(7), ADB8=>RdAddress(6), 
            ADB7=>RdAddress(5), ADB6=>RdAddress(4), ADB5=>RdAddress(3), 
            ADB4=>RdAddress(2), ADB3=>RdAddress(1), ADB2=>RdAddress(0), 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>RdAddress(11), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>mdout1_0_3_1, DOB2=>mdout1_0_2_1, DOB1=>mdout1_0_1_1, 
            DOB0=>mdout1_0_0_1);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    ROM_1_0_0_0: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_17=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_16=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_15=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_14=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_13=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_12=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_11=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_10=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_09=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_08=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_07=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_06=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_05=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_04=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_03=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_02=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_01=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_00=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        CSDECODE_B=> "0b010", CSDECODE_A=> "0b010", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  9, 
        DATA_WIDTH_A=>  9)
        port map (DIA8=>scuba_vlo, DIA7=>Data(7), DIA6=>Data(6), 
            DIA5=>Data(5), DIA4=>Data(4), DIA3=>Data(3), DIA2=>Data(2), 
            DIA1=>Data(1), DIA0=>Data(0), ADA12=>WrAddress(9), 
            ADA11=>WrAddress(8), ADA10=>WrAddress(7), ADA9=>WrAddress(6), 
            ADA8=>WrAddress(5), ADA7=>WrAddress(4), ADA6=>WrAddress(3), 
            ADA5=>WrAddress(2), ADA4=>WrAddress(1), ADA3=>WrAddress(0), 
            ADA2=>scuba_vlo, ADA1=>scuba_vlo, ADA0=>scuba_vhi, 
            CEA=>WrClockEn, OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, 
            CSA2=>scuba_vlo, CSA1=>WrAddress(11), CSA0=>WrAddress(10), 
            RSTA=>Reset, DIB8=>scuba_vlo, DIB7=>scuba_vlo, 
            DIB6=>scuba_vlo, DIB5=>scuba_vlo, DIB4=>scuba_vlo, 
            DIB3=>scuba_vlo, DIB2=>scuba_vlo, DIB1=>scuba_vlo, 
            DIB0=>scuba_vlo, ADB12=>RdAddress(9), ADB11=>RdAddress(8), 
            ADB10=>RdAddress(7), ADB9=>RdAddress(6), ADB8=>RdAddress(5), 
            ADB7=>RdAddress(4), ADB6=>RdAddress(3), ADB5=>RdAddress(2), 
            ADB4=>RdAddress(1), ADB3=>RdAddress(0), ADB2=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>RdAddress(11), CSB0=>RdAddress(10), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>mdout1_0_7, DOB6=>mdout1_0_6, 
            DOB5=>mdout1_0_5, DOB4=>mdout1_0_4, DOB3=>mdout1_0_3_2, 
            DOB2=>mdout1_0_2_2, DOB1=>mdout1_0_1_2, DOB0=>mdout1_0_0_2);

    FF_1: FD1P3DX
        port map (D=>RdAddress(10), SP=>RdClockEn, CK=>RdClock, 
            CD=>scuba_vlo, Q=>raddr10_ff);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    FF_0: FD1P3DX
        port map (D=>RdAddress(11), SP=>RdClockEn, CK=>RdClock, 
            CD=>scuba_vlo, Q=>raddr11_ff);

    mux_7: MUX21
        port map (D0=>mdout1_0_0, D1=>mdout1_0_0_2, SD=>raddr11_ff, 
            Z=>Q(0));

    mux_6: MUX21
        port map (D0=>mdout1_0_1, D1=>mdout1_0_1_2, SD=>raddr11_ff, 
            Z=>Q(1));

    mux_5: MUX21
        port map (D0=>mdout1_0_2, D1=>mdout1_0_2_2, SD=>raddr11_ff, 
            Z=>Q(2));

    mux_4: MUX21
        port map (D0=>mdout1_0_3, D1=>mdout1_0_3_2, SD=>raddr11_ff, 
            Z=>Q(3));

    mux_3: MUX21
        port map (D0=>mdout1_0_0_1, D1=>mdout1_0_4, SD=>raddr11_ff, 
            Z=>Q(4));

    mux_2: MUX21
        port map (D0=>mdout1_0_1_1, D1=>mdout1_0_5, SD=>raddr11_ff, 
            Z=>Q(5));

    mux_1: MUX21
        port map (D0=>mdout1_0_2_1, D1=>mdout1_0_6, SD=>raddr11_ff, 
            Z=>Q(6));

    mux_0: MUX21
        port map (D0=>mdout1_0_3_1, D1=>mdout1_0_7, SD=>raddr11_ff, 
            Z=>Q(7));

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of ROM is
    for Structure
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:MUX21 use entity MACHXO2.MUX21(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:DP8KC use entity MACHXO2.DP8KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
