-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 6.5
--C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n ROM -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type bram -wp 10 -rp 0011 -rdata_width 8 -data_width 8 -num_rows 3072 -cascade 11 -memfile c:/kevan/a3041/p3041/rom.mem -memformat hex 

-- Fri Aug 18 15:45:22 2023

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity ROM is
    port (
        WrAddress: in  std_logic_vector(11 downto 0); 
        RdAddress: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        WE: in  std_logic; 
        RdClock: in  std_logic; 
        RdClockEn: in  std_logic; 
        Reset: in  std_logic; 
        WrClock: in  std_logic; 
        WrClockEn: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0));
end ROM;

architecture Structure of ROM is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal raddr10_ff: std_logic;
    signal scuba_vlo: std_logic;
    signal mdout1_0_0_2: std_logic;
    signal mdout1_0_0: std_logic;
    signal mdout1_0_1_2: std_logic;
    signal mdout1_0_1: std_logic;
    signal mdout1_0_2_2: std_logic;
    signal mdout1_0_2: std_logic;
    signal mdout1_0_3_2: std_logic;
    signal mdout1_0_3: std_logic;
    signal mdout1_0_4: std_logic;
    signal mdout1_0_0_1: std_logic;
    signal mdout1_0_5: std_logic;
    signal mdout1_0_1_1: std_logic;
    signal mdout1_0_6: std_logic;
    signal mdout1_0_2_1: std_logic;
    signal raddr11_ff: std_logic;
    signal mdout1_0_7: std_logic;
    signal mdout1_0_3_1: std_logic;

    -- local component declarations
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component MUX21
        port (D0: in  std_logic; D1: in  std_logic; SD: in  std_logic; 
            Z: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component DP8KC
        generic (INIT_DATA : in String; INITVAL_1F : in String; 
                INITVAL_1E : in String; INITVAL_1D : in String; 
                INITVAL_1C : in String; INITVAL_1B : in String; 
                INITVAL_1A : in String; INITVAL_19 : in String; 
                INITVAL_18 : in String; INITVAL_17 : in String; 
                INITVAL_16 : in String; INITVAL_15 : in String; 
                INITVAL_14 : in String; INITVAL_13 : in String; 
                INITVAL_12 : in String; INITVAL_11 : in String; 
                INITVAL_10 : in String; INITVAL_0F : in String; 
                INITVAL_0E : in String; INITVAL_0D : in String; 
                INITVAL_0C : in String; INITVAL_0B : in String; 
                INITVAL_0A : in String; INITVAL_09 : in String; 
                INITVAL_08 : in String; INITVAL_07 : in String; 
                INITVAL_06 : in String; INITVAL_05 : in String; 
                INITVAL_04 : in String; INITVAL_03 : in String; 
                INITVAL_02 : in String; INITVAL_01 : in String; 
                INITVAL_00 : in String; ASYNC_RESET_RELEASE : in String; 
                RESETMODE : in String; GSR : in String; 
                WRITEMODE_B : in String; WRITEMODE_A : in String; 
                CSDECODE_B : in String; CSDECODE_A : in String; 
                REGMODE_B : in String; REGMODE_A : in String; 
                DATA_WIDTH_B : in Integer; DATA_WIDTH_A : in Integer);
        port (DIA8: in  std_logic; DIA7: in  std_logic; 
            DIA6: in  std_logic; DIA5: in  std_logic; 
            DIA4: in  std_logic; DIA3: in  std_logic; 
            DIA2: in  std_logic; DIA1: in  std_logic; 
            DIA0: in  std_logic; ADA12: in  std_logic; 
            ADA11: in  std_logic; ADA10: in  std_logic; 
            ADA9: in  std_logic; ADA8: in  std_logic; 
            ADA7: in  std_logic; ADA6: in  std_logic; 
            ADA5: in  std_logic; ADA4: in  std_logic; 
            ADA3: in  std_logic; ADA2: in  std_logic; 
            ADA1: in  std_logic; ADA0: in  std_logic; CEA: in  std_logic; 
            OCEA: in  std_logic; CLKA: in  std_logic; WEA: in  std_logic; 
            CSA2: in  std_logic; CSA1: in  std_logic; 
            CSA0: in  std_logic; RSTA: in  std_logic; 
            DIB8: in  std_logic; DIB7: in  std_logic; 
            DIB6: in  std_logic; DIB5: in  std_logic; 
            DIB4: in  std_logic; DIB3: in  std_logic; 
            DIB2: in  std_logic; DIB1: in  std_logic; 
            DIB0: in  std_logic; ADB12: in  std_logic; 
            ADB11: in  std_logic; ADB10: in  std_logic; 
            ADB9: in  std_logic; ADB8: in  std_logic; 
            ADB7: in  std_logic; ADB6: in  std_logic; 
            ADB5: in  std_logic; ADB4: in  std_logic; 
            ADB3: in  std_logic; ADB2: in  std_logic; 
            ADB1: in  std_logic; ADB0: in  std_logic; CEB: in  std_logic; 
            OCEB: in  std_logic; CLKB: in  std_logic; WEB: in  std_logic; 
            CSB2: in  std_logic; CSB1: in  std_logic; 
            CSB0: in  std_logic; RSTB: in  std_logic; 
            DOA8: out  std_logic; DOA7: out  std_logic; 
            DOA6: out  std_logic; DOA5: out  std_logic; 
            DOA4: out  std_logic; DOA3: out  std_logic; 
            DOA2: out  std_logic; DOA1: out  std_logic; 
            DOA0: out  std_logic; DOB8: out  std_logic; 
            DOB7: out  std_logic; DOB6: out  std_logic; 
            DOB5: out  std_logic; DOB4: out  std_logic; 
            DOB3: out  std_logic; DOB2: out  std_logic; 
            DOB1: out  std_logic; DOB0: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of ROM_0_0_0_2 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_0_0_0_2 : label is "rom.mem";
    attribute MEM_LPC_FILE of ROM_0_0_1_1 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_0_0_1_1 : label is "rom.mem";
    attribute MEM_LPC_FILE of ROM_1_0_0_0 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_1_0_0_0 : label is "rom.mem";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    ROM_0_0_0_2: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x0000000000000000000000000000000000000000000000000000000000000000000000010510B050", 
        INITVAL_17=> "0x01052002900905200200094481EA1900A780A00310AD10704C0A8600A076008700A257008F506211", 
        INITVAL_16=> "0x008F506219008C410C2806A310248407050008851E030100051504100A100B6840D0500025203280", 
        INITVAL_15=> "0x00208000011603314E0D10A080A001046450C2851621808A05000180B031108A00A20610A0009651", 
        INITVAL_14=> "0x03057022841405000A05020200A04300A000A22402C08040200823400A000822502C080401008234", 
        INITVAL_13=> "0x02C08040000860100204040500E604020560804100204000540A0410040406A300300418051008D0", 
        INITVAL_12=> "0x0A4040205001C0505C040203009E0505E0402040080050000402050082850861808C540641010AD8", 
        INITVAL_11=> "0x0A20E00EA70000508A74080040205A0204000AE00080714E0D10A080A001046450D0180BA1110858", 
        INITVAL_10=> "0x0AA85020F204011008F204010008A402A18122050CA18134420CA6A082F210A1812A420AA6A082C1", 
        INITVAL_0F=> "0x10A1812A4208A6A0825110A18136050CA1812A3206A6A082380BC13108A40260500C200A05F1E638", 
        INITVAL_0E=> "0x0A23310823060150309610A000AC51112D3044561481310A230704710A01002850E21808A051405E", 
        INITVAL_0D=> "0x00AF00A005000100B20502051112800AC51112700AC51112600AC51112500AC51112400AC5111230", 
        INITVAL_0C=> "0x0AC51112200AC51112100AC51112000AC5111203042561481310AD10704610A900A0050309C06405", 
        INITVAL_0B=> "0x0D4421EA031482F0A04F042120480302A120480402C51112400CA18126060C0B808A0A1080403445", 
        INITVAL_0A=> "0x000500E684020520A884030520628410C540641010AD80A2001CEA700A67040B80A20810A03198CC", 
        INITVAL_09=> "0x1704A10AF31704910AA808EF01705000EF01705201A240A00700A6002A060E206016840A0A808C50", 
        INITVAL_08=> "0x0F4700E40B10A1011052078CC182041505F06204130501087E002850FC0110A7F016850007F01685", 
        INITVAL_07=> "0x0400714E07040B80A20810A13198CC0204910AB0094851E61008EF01705000EF0170520007A0E010", 
        INITVAL_06=> "0x0A005000210800500E000820502A100807B00ED80A085000180BC11108560005000014040500E404", 
        INITVAL_05=> "0x060510A6040021300A06040500BEF310230032041705101085002CC180041621810A000022003404", 
        INITVAL_04=> "0x1621810A00002200320413050014850204410A10002310248403058062840D050008A00A20500A00", 
        INITVAL_03=> "0x1024200A070404300A070604400A1508048026010A048022180AE11108A00AC85000810980500EC0", 
        INITVAL_02=> "0x09A0502AD009A03002A008205020F009C0500EE009E0500EF00800502A0008885040810641210865", 
        INITVAL_01=> "0x03051062840E0851B051000A7002200DA85000851D04D10A101F050022101E0D80A085000100F470", 
        INITVAL_00=> "0x06A620C255002501005601806120330A00300A6000068008201802600A000060800C5300EE002851", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(3), 
            DIA2=>Data(2), DIA1=>Data(1), DIA0=>Data(0), 
            ADA12=>WrAddress(10), ADA11=>WrAddress(9), 
            ADA10=>WrAddress(8), ADA9=>WrAddress(7), ADA8=>WrAddress(6), 
            ADA7=>WrAddress(5), ADA6=>WrAddress(4), ADA5=>WrAddress(3), 
            ADA4=>WrAddress(2), ADA3=>WrAddress(1), ADA2=>WrAddress(0), 
            ADA1=>scuba_vlo, ADA0=>scuba_vlo, CEA=>WrClockEn, 
            OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>WrAddress(11), RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>RdAddress(10), ADB11=>RdAddress(9), 
            ADB10=>RdAddress(8), ADB9=>RdAddress(7), ADB8=>RdAddress(6), 
            ADB7=>RdAddress(5), ADB6=>RdAddress(4), ADB5=>RdAddress(3), 
            ADB4=>RdAddress(2), ADB3=>RdAddress(1), ADB2=>RdAddress(0), 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>RdAddress(11), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>mdout1_0_3, DOB2=>mdout1_0_2, DOB1=>mdout1_0_1, 
            DOB0=>mdout1_0_0);

    ROM_0_0_1_1: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000000140000010", 
        INITVAL_17=> "0x0340000800034000084002E001C0000021002010002F70001E00000020400020002040002E000071", 
        INITVAL_16=> "0x002E0000700025001200160000E20100010020011E2400060102013002400220100010030000CA10", 
        INITVAL_15=> "0x02622020010200100630002100201306633062011EE1002201002100207100200020100020002A00", 
        INITVAL_14=> "0x0201F0E2010001002201002100262100243046230400006450026210024304623040000645002623", 
        INITVAL_13=> "0x040000645002623046010A010080010A01400013040010A014000130400108000080010001000200", 
        INITVAL_12=> "0x02001020100200108001064000200108001064000220108201064000220100E10024220442100200", 
        INITVAL_11=> "0x02010044030660116E700060106017060130027300222006300021002013066330661003E7100210", 
        INITVAL_10=> "0x02001002F000042002F00004200220014000A801034000A6000081200030014000A20000812000F0", 
        INITVAL_0F=> "0x014000A00000812000C0014000A001034000BE00008120000003E700022000801064400262F0E200", 
        INITVAL_0E=> "0x02070002D00004A0005100240022A000AD00004104000002070001100262022011EE100220100010", 
        INITVAL_0D=> "0x00200022010021002001002A000A00022A000A00022A000A00022A000A00022A000A00022A000A00", 
        INITVAL_0C=> "0x022A000A00022A000A00022A000A00022A000AA00004104000002F700010002000201A0005100004", 
        INITVAL_0B=> "0x026001E8320600F0862F000F000832064F000832064A000A32034000A62106410026210020002600", 
        INITVAL_0A=> "0x04010082010401008201020100E2010442204421002000201200403066360620002010002070EE77", 
        INITVAL_09=> "0x0201000207020100021002CF10001002CF100010028000640406432008320C413042010641002422", 
        INITVAL_08=> "0x040330C61000201000100EE770E801000100E8010001000261020010C2100026F020010026F02001", 
        INITVAL_07=> "0x00222006360620002010002070EE7708010002000200100E4002CF10001002CF1000100242006620", 
        INITVAL_06=> "0x02401002C0004010082002401008200242006600022010021003E710023308010032000801008801", 
        INITVAL_05=> "0x080100880112004002320801305E710E0000800100010020010C8770E0010A000002610A00008001", 
        INITVAL_04=> "0x0A00000221080000800100010020010801000201120000E001020100E20100010002000201100201", 
        INITVAL_03=> "0x0200100204020110020402011002240201100004020110001003E710020002001002100000100800", 
        INITVAL_02=> "0x020010480003A000080002201002A000001008000200100800022010481002001002100007000222", 
        INITVAL_01=> "0x020100E20104201000100240306650000010024400010002010001304C3200200022010022204033", 
        INITVAL_00=> "0x0663304621000320E62304E3206006064040643208622000320E6230462002620024220446000E00", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(7), 
            DIA2=>Data(6), DIA1=>Data(5), DIA0=>Data(4), 
            ADA12=>WrAddress(10), ADA11=>WrAddress(9), 
            ADA10=>WrAddress(8), ADA9=>WrAddress(7), ADA8=>WrAddress(6), 
            ADA7=>WrAddress(5), ADA6=>WrAddress(4), ADA5=>WrAddress(3), 
            ADA4=>WrAddress(2), ADA3=>WrAddress(1), ADA2=>WrAddress(0), 
            ADA1=>scuba_vlo, ADA0=>scuba_vlo, CEA=>WrClockEn, 
            OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>WrAddress(11), RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>RdAddress(10), ADB11=>RdAddress(9), 
            ADB10=>RdAddress(8), ADB9=>RdAddress(7), ADB8=>RdAddress(6), 
            ADB7=>RdAddress(5), ADB6=>RdAddress(4), ADB5=>RdAddress(3), 
            ADB4=>RdAddress(2), ADB3=>RdAddress(1), ADB2=>RdAddress(0), 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>RdAddress(11), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>mdout1_0_3_1, DOB2=>mdout1_0_2_1, DOB1=>mdout1_0_1_1, 
            DOB0=>mdout1_0_0_1);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    ROM_1_0_0_0: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_17=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_16=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_15=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_14=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_13=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_12=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_11=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_10=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_09=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_08=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_07=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_06=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_05=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_04=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_03=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_02=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_01=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_00=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        CSDECODE_B=> "0b010", CSDECODE_A=> "0b010", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  9, 
        DATA_WIDTH_A=>  9)
        port map (DIA8=>scuba_vlo, DIA7=>Data(7), DIA6=>Data(6), 
            DIA5=>Data(5), DIA4=>Data(4), DIA3=>Data(3), DIA2=>Data(2), 
            DIA1=>Data(1), DIA0=>Data(0), ADA12=>WrAddress(9), 
            ADA11=>WrAddress(8), ADA10=>WrAddress(7), ADA9=>WrAddress(6), 
            ADA8=>WrAddress(5), ADA7=>WrAddress(4), ADA6=>WrAddress(3), 
            ADA5=>WrAddress(2), ADA4=>WrAddress(1), ADA3=>WrAddress(0), 
            ADA2=>scuba_vlo, ADA1=>scuba_vlo, ADA0=>scuba_vhi, 
            CEA=>WrClockEn, OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, 
            CSA2=>scuba_vlo, CSA1=>WrAddress(11), CSA0=>WrAddress(10), 
            RSTA=>Reset, DIB8=>scuba_vlo, DIB7=>scuba_vlo, 
            DIB6=>scuba_vlo, DIB5=>scuba_vlo, DIB4=>scuba_vlo, 
            DIB3=>scuba_vlo, DIB2=>scuba_vlo, DIB1=>scuba_vlo, 
            DIB0=>scuba_vlo, ADB12=>RdAddress(9), ADB11=>RdAddress(8), 
            ADB10=>RdAddress(7), ADB9=>RdAddress(6), ADB8=>RdAddress(5), 
            ADB7=>RdAddress(4), ADB6=>RdAddress(3), ADB5=>RdAddress(2), 
            ADB4=>RdAddress(1), ADB3=>RdAddress(0), ADB2=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>RdAddress(11), CSB0=>RdAddress(10), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>mdout1_0_7, DOB6=>mdout1_0_6, 
            DOB5=>mdout1_0_5, DOB4=>mdout1_0_4, DOB3=>mdout1_0_3_2, 
            DOB2=>mdout1_0_2_2, DOB1=>mdout1_0_1_2, DOB0=>mdout1_0_0_2);

    FF_1: FD1P3DX
        port map (D=>RdAddress(10), SP=>RdClockEn, CK=>RdClock, 
            CD=>scuba_vlo, Q=>raddr10_ff);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    FF_0: FD1P3DX
        port map (D=>RdAddress(11), SP=>RdClockEn, CK=>RdClock, 
            CD=>scuba_vlo, Q=>raddr11_ff);

    mux_7: MUX21
        port map (D0=>mdout1_0_0, D1=>mdout1_0_0_2, SD=>raddr11_ff, 
            Z=>Q(0));

    mux_6: MUX21
        port map (D0=>mdout1_0_1, D1=>mdout1_0_1_2, SD=>raddr11_ff, 
            Z=>Q(1));

    mux_5: MUX21
        port map (D0=>mdout1_0_2, D1=>mdout1_0_2_2, SD=>raddr11_ff, 
            Z=>Q(2));

    mux_4: MUX21
        port map (D0=>mdout1_0_3, D1=>mdout1_0_3_2, SD=>raddr11_ff, 
            Z=>Q(3));

    mux_3: MUX21
        port map (D0=>mdout1_0_0_1, D1=>mdout1_0_4, SD=>raddr11_ff, 
            Z=>Q(4));

    mux_2: MUX21
        port map (D0=>mdout1_0_1_1, D1=>mdout1_0_5, SD=>raddr11_ff, 
            Z=>Q(5));

    mux_1: MUX21
        port map (D0=>mdout1_0_2_1, D1=>mdout1_0_6, SD=>raddr11_ff, 
            Z=>Q(6));

    mux_0: MUX21
        port map (D0=>mdout1_0_3_1, D1=>mdout1_0_7, SD=>raddr11_ff, 
            Z=>Q(7));

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of ROM is
    for Structure
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:MUX21 use entity MACHXO2.MUX21(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:DP8KC use entity MACHXO2.DP8KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
