-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 6.5
--C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n ROM -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type bram -wp 10 -rp 0011 -rdata_width 8 -data_width 8 -num_rows 3072 -cascade 11 -memfile c:/kevan/a3041/p3041/rom.mem -memformat hex 

-- Tue Aug 29 20:40:19 2023

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity ROM is
    port (
        WrAddress: in  std_logic_vector(11 downto 0); 
        RdAddress: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        WE: in  std_logic; 
        RdClock: in  std_logic; 
        RdClockEn: in  std_logic; 
        Reset: in  std_logic; 
        WrClock: in  std_logic; 
        WrClockEn: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0));
end ROM;

architecture Structure of ROM is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal raddr10_ff: std_logic;
    signal scuba_vlo: std_logic;
    signal mdout1_0_0_2: std_logic;
    signal mdout1_0_0: std_logic;
    signal mdout1_0_1_2: std_logic;
    signal mdout1_0_1: std_logic;
    signal mdout1_0_2_2: std_logic;
    signal mdout1_0_2: std_logic;
    signal mdout1_0_3_2: std_logic;
    signal mdout1_0_3: std_logic;
    signal mdout1_0_4: std_logic;
    signal mdout1_0_0_1: std_logic;
    signal mdout1_0_5: std_logic;
    signal mdout1_0_1_1: std_logic;
    signal mdout1_0_6: std_logic;
    signal mdout1_0_2_1: std_logic;
    signal raddr11_ff: std_logic;
    signal mdout1_0_7: std_logic;
    signal mdout1_0_3_1: std_logic;

    -- local component declarations
    component FD1P3DX
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component MUX21
        port (D0: in  std_logic; D1: in  std_logic; SD: in  std_logic; 
            Z: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component DP8KC
        generic (INIT_DATA : in String; INITVAL_1F : in String; 
                INITVAL_1E : in String; INITVAL_1D : in String; 
                INITVAL_1C : in String; INITVAL_1B : in String; 
                INITVAL_1A : in String; INITVAL_19 : in String; 
                INITVAL_18 : in String; INITVAL_17 : in String; 
                INITVAL_16 : in String; INITVAL_15 : in String; 
                INITVAL_14 : in String; INITVAL_13 : in String; 
                INITVAL_12 : in String; INITVAL_11 : in String; 
                INITVAL_10 : in String; INITVAL_0F : in String; 
                INITVAL_0E : in String; INITVAL_0D : in String; 
                INITVAL_0C : in String; INITVAL_0B : in String; 
                INITVAL_0A : in String; INITVAL_09 : in String; 
                INITVAL_08 : in String; INITVAL_07 : in String; 
                INITVAL_06 : in String; INITVAL_05 : in String; 
                INITVAL_04 : in String; INITVAL_03 : in String; 
                INITVAL_02 : in String; INITVAL_01 : in String; 
                INITVAL_00 : in String; ASYNC_RESET_RELEASE : in String; 
                RESETMODE : in String; GSR : in String; 
                WRITEMODE_B : in String; WRITEMODE_A : in String; 
                CSDECODE_B : in String; CSDECODE_A : in String; 
                REGMODE_B : in String; REGMODE_A : in String; 
                DATA_WIDTH_B : in Integer; DATA_WIDTH_A : in Integer);
        port (DIA8: in  std_logic; DIA7: in  std_logic; 
            DIA6: in  std_logic; DIA5: in  std_logic; 
            DIA4: in  std_logic; DIA3: in  std_logic; 
            DIA2: in  std_logic; DIA1: in  std_logic; 
            DIA0: in  std_logic; ADA12: in  std_logic; 
            ADA11: in  std_logic; ADA10: in  std_logic; 
            ADA9: in  std_logic; ADA8: in  std_logic; 
            ADA7: in  std_logic; ADA6: in  std_logic; 
            ADA5: in  std_logic; ADA4: in  std_logic; 
            ADA3: in  std_logic; ADA2: in  std_logic; 
            ADA1: in  std_logic; ADA0: in  std_logic; CEA: in  std_logic; 
            OCEA: in  std_logic; CLKA: in  std_logic; WEA: in  std_logic; 
            CSA2: in  std_logic; CSA1: in  std_logic; 
            CSA0: in  std_logic; RSTA: in  std_logic; 
            DIB8: in  std_logic; DIB7: in  std_logic; 
            DIB6: in  std_logic; DIB5: in  std_logic; 
            DIB4: in  std_logic; DIB3: in  std_logic; 
            DIB2: in  std_logic; DIB1: in  std_logic; 
            DIB0: in  std_logic; ADB12: in  std_logic; 
            ADB11: in  std_logic; ADB10: in  std_logic; 
            ADB9: in  std_logic; ADB8: in  std_logic; 
            ADB7: in  std_logic; ADB6: in  std_logic; 
            ADB5: in  std_logic; ADB4: in  std_logic; 
            ADB3: in  std_logic; ADB2: in  std_logic; 
            ADB1: in  std_logic; ADB0: in  std_logic; CEB: in  std_logic; 
            OCEB: in  std_logic; CLKB: in  std_logic; WEB: in  std_logic; 
            CSB2: in  std_logic; CSB1: in  std_logic; 
            CSB0: in  std_logic; RSTB: in  std_logic; 
            DOA8: out  std_logic; DOA7: out  std_logic; 
            DOA6: out  std_logic; DOA5: out  std_logic; 
            DOA4: out  std_logic; DOA3: out  std_logic; 
            DOA2: out  std_logic; DOA1: out  std_logic; 
            DOA0: out  std_logic; DOB8: out  std_logic; 
            DOB7: out  std_logic; DOB6: out  std_logic; 
            DOB5: out  std_logic; DOB4: out  std_logic; 
            DOB3: out  std_logic; DOB2: out  std_logic; 
            DOB1: out  std_logic; DOB0: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of ROM_0_0_0_2 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_0_0_0_2 : label is "rom.mem";
    attribute MEM_LPC_FILE of ROM_0_0_1_1 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_0_0_1_1 : label is "rom.mem";
    attribute MEM_LPC_FILE of ROM_1_0_0_0 : label is "ROM.lpc";
    attribute MEM_INIT_FILE of ROM_1_0_0_0 : label is "rom.mem";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    ROM_0_0_0_2: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000000EA1510A00", 
        INITVAL_17=> "0x0EA20032040EA20020041A8800A2900AE85000380BA13108D508C0500E6008E0502A700820500005", 
        INITVAL_16=> "0x06211008050621900852104530222808685000480BE03010000B4840205100AB8080C5140800AC85", 
        INITVAL_15=> "0x0008504298000101000003603074701B05010A00024340AC500A00A00A1014A1A00A000A05100405", 
        INITVAL_14=> "0x008300A005024410C08200404026400A004024510C08200204026410C08200004060100204F09020", 
        INITVAL_13=> "0x0A073008100AC4008201008000A850082020080506018008C00A2041A05200865086210105D10A10", 
        INITVAL_12=> "0x1C07A0E0000A85A0880008205142040005E000400F4701B05010A00024340AC8510A580A20606401", 
        INITVAL_11=> "0x02046064010004508241112800AC4111254050560A81208414030A912C0C0420508601082890C818", 
        INITVAL_10=> "0x120420EA6508241112100AC411129404C560A81E050411124404A560A81B0504111244048560A814", 
        INITVAL_0F=> "0x03041112B00AC4111244046560A81310AE107045082300A06200A051FE3310A13070410660108289", 
        INITVAL_0E=> "0x0D05000A640309C064250CA4107052066840F050020500B4051C05F00A000A00100A900A20403098", 
        INITVAL_0D=> "0x00A640309700A640309600A640309500A640309400A640309300A640309200A640309100A6403090", 
        INITVAL_0C=> "0x00A640309F064150CA410705D026840D05900A0008289066200AC5405E5006A421EA040C61806440", 
        INITVAL_0B=> "0x0625806440082640309400C41112300CC0B1085015040082540A00500E380820504A480906508621", 
        INITVAL_0A=> "0x0105D10A1001C7A0E0560E40B10A1011050078CC196841505F076841305A1087F016850007F01685", 
        INITVAL_09=> "0x040C208A000E056002500CE100C0B808A0A1086500EA700E201705101085046CC19810094851E610", 
        INITVAL_08=> "0x09285010471C0180AEE0030571E0B80A0071E0B80A4000F4700E40B10A1011051078CC182041305B", 
        INITVAL_07=> "0x008A80BE310087F016850007F016850400714E0100A000A001028000A070008100A251008071607D", 
        INITVAL_06=> "0x10A080A00110AE1030450C005000F10840500E200860502A3009E11060500C40500AFF06E1300290", 
        INITVAL_05=> "0x0968502008114130228009085002CC180041E21810A0008220034041E21810A00082200320413050", 
        INITVAL_04=> "0x014850204410A101E231024841405100A05000C10840500E200860500E300880502A400981300250", 
        INITVAL_03=> "0x098111405610A001824C00A071804D00A151A04610A0009E03002A009C0505C040203009E0505E04", 
        INITVAL_02=> "0x02040080050000402050082050203009C0500EE009E0500EF00800502A0008885040C10641210865", 
        INITVAL_01=> "0x03051062840E0851B051000A7002200DA85000851D04D10A101F050022101E0D80A085000100F470", 
        INITVAL_00=> "0x06A620C255002501005601806120330A00300A6000068008201802600A000060800C5300EE003651", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(3), 
            DIA2=>Data(2), DIA1=>Data(1), DIA0=>Data(0), 
            ADA12=>WrAddress(10), ADA11=>WrAddress(9), 
            ADA10=>WrAddress(8), ADA9=>WrAddress(7), ADA8=>WrAddress(6), 
            ADA7=>WrAddress(5), ADA6=>WrAddress(4), ADA5=>WrAddress(3), 
            ADA4=>WrAddress(2), ADA3=>WrAddress(1), ADA2=>WrAddress(0), 
            ADA1=>scuba_vlo, ADA0=>scuba_vlo, CEA=>WrClockEn, 
            OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>WrAddress(11), RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>RdAddress(10), ADB11=>RdAddress(9), 
            ADB10=>RdAddress(8), ADB9=>RdAddress(7), ADB8=>RdAddress(6), 
            ADB7=>RdAddress(5), ADB6=>RdAddress(4), ADB5=>RdAddress(3), 
            ADB4=>RdAddress(2), ADB3=>RdAddress(1), ADB2=>RdAddress(0), 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>RdAddress(11), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>mdout1_0_3, DOB2=>mdout1_0_2, DOB1=>mdout1_0_1, 
            DOB0=>mdout1_0_0);

    ROM_0_0_1_1: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000001400000201", 
        INITVAL_17=> "0x140000800114000088011600F00000022010020003E70002E00000100800020010080002201002F0", 
        INITVAL_16=> "0x00071002F000070002B00160000E10020010020003E1400030022010601400210020010024002001", 
        INITVAL_15=> "0x0027000C51002320420002200020330001100201066330661002010002010A000002010201002201", 
        INITVAL_14=> "0x0641002832064320000304A010641002832064320000304A01064320000304A01064320601900050", 
        INITVAL_13=> "0x02040002500280002620002500280002620002500004000200020010001000222044220201000201", 
        INITVAL_12=> "0x00420066300367B00030026010E60106017060120403300011002010663306631002000201100004", 
        INITVAL_11=> "0x040110000404017000C000A40022C000A80000410E0050006C000550220002627000041800503800", 
        INITVAL_10=> "0x0AC0000817000C000A40022C000A30000410E005000C000A20000410E001000C000A10000410E00E", 
        INITVAL_0F=> "0x000C000A00022C000A00000410E000002F7000170004002624002321EE10002070001E0000418005", 
        INITVAL_0E=> "0x020140021C0005E0000402E00000100E001020160421002001000100021002011002000201C00050", 
        INITVAL_0D=> "0x0021C000500021C000500021C000500021C000500021C000500021C000500021C000500021C00050", 
        INITVAL_0C=> "0x0021C0005A0000402E000001F0E001000100020118005060000828001E43050001E8320200000043", 
        INITVAL_0B=> "0x04620000430462C00053042C000A3202621002320201000280004010081002401008100242204422", 
        INITVAL_0A=> "0x020100020104020066330C61000201000100EE770E201000100E201000110026F020010026F02001", 
        INITVAL_09=> "0x0026000620086230404304C210641002621002220440306C31000100200100E770EE400200100E40", 
        INITVAL_08=> "0x02001000160220002C11000161E200020161E20002012040330C61000201000100EE770E80100010", 
        INITVAL_07=> "0x00200020740026F020010026F020010022200632002200201E000200204200220020420022200630", 
        INITVAL_06=> "0x0021002011002F70201306801002A000801008400280100840034000801304801064F70320000800", 
        INITVAL_05=> "0x020010020000E0000E40020010C8770E0010C000002610C000080010C000002210A0000800100010", 
        INITVAL_04=> "0x020010801000201140000E0010001002201002200020100810022010081002201048100240000810", 
        INITVAL_03=> "0x02400000100020104000002040001000224000100020003E00008000200108001064000200108001", 
        INITVAL_02=> "0x0640002201082010640002201002D000001008000200100800022010481002001002200007000222", 
        INITVAL_01=> "0x020100E20104201000100240306650000010024400010002010001304C3200200022010022204033", 
        INITVAL_00=> "0x0663304621000320E62304E3206006064040643208622000320E6230462002620024220446000C00", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(7), 
            DIA2=>Data(6), DIA1=>Data(5), DIA0=>Data(4), 
            ADA12=>WrAddress(10), ADA11=>WrAddress(9), 
            ADA10=>WrAddress(8), ADA9=>WrAddress(7), ADA8=>WrAddress(6), 
            ADA7=>WrAddress(5), ADA6=>WrAddress(4), ADA5=>WrAddress(3), 
            ADA4=>WrAddress(2), ADA3=>WrAddress(1), ADA2=>WrAddress(0), 
            ADA1=>scuba_vlo, ADA0=>scuba_vlo, CEA=>WrClockEn, 
            OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, CSA2=>scuba_vlo, 
            CSA1=>scuba_vlo, CSA0=>WrAddress(11), RSTA=>Reset, 
            DIB8=>scuba_vlo, DIB7=>scuba_vlo, DIB6=>scuba_vlo, 
            DIB5=>scuba_vlo, DIB4=>scuba_vlo, DIB3=>scuba_vlo, 
            DIB2=>scuba_vlo, DIB1=>scuba_vlo, DIB0=>scuba_vlo, 
            ADB12=>RdAddress(10), ADB11=>RdAddress(9), 
            ADB10=>RdAddress(8), ADB9=>RdAddress(7), ADB8=>RdAddress(6), 
            ADB7=>RdAddress(5), ADB6=>RdAddress(4), ADB5=>RdAddress(3), 
            ADB4=>RdAddress(2), ADB3=>RdAddress(1), ADB2=>RdAddress(0), 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>RdAddress(11), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>mdout1_0_3_1, DOB2=>mdout1_0_2_1, DOB1=>mdout1_0_1_1, 
            DOB0=>mdout1_0_0_1);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    ROM_1_0_0_0: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_17=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_16=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_15=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_14=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_13=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_12=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_11=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_10=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_0A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_09=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_08=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_07=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_06=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_05=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_04=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_03=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_02=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_01=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        INITVAL_00=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000", 
        CSDECODE_B=> "0b010", CSDECODE_A=> "0b010", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  9, 
        DATA_WIDTH_A=>  9)
        port map (DIA8=>scuba_vlo, DIA7=>Data(7), DIA6=>Data(6), 
            DIA5=>Data(5), DIA4=>Data(4), DIA3=>Data(3), DIA2=>Data(2), 
            DIA1=>Data(1), DIA0=>Data(0), ADA12=>WrAddress(9), 
            ADA11=>WrAddress(8), ADA10=>WrAddress(7), ADA9=>WrAddress(6), 
            ADA8=>WrAddress(5), ADA7=>WrAddress(4), ADA6=>WrAddress(3), 
            ADA5=>WrAddress(2), ADA4=>WrAddress(1), ADA3=>WrAddress(0), 
            ADA2=>scuba_vlo, ADA1=>scuba_vlo, ADA0=>scuba_vhi, 
            CEA=>WrClockEn, OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE, 
            CSA2=>scuba_vlo, CSA1=>WrAddress(11), CSA0=>WrAddress(10), 
            RSTA=>Reset, DIB8=>scuba_vlo, DIB7=>scuba_vlo, 
            DIB6=>scuba_vlo, DIB5=>scuba_vlo, DIB4=>scuba_vlo, 
            DIB3=>scuba_vlo, DIB2=>scuba_vlo, DIB1=>scuba_vlo, 
            DIB0=>scuba_vlo, ADB12=>RdAddress(9), ADB11=>RdAddress(8), 
            ADB10=>RdAddress(7), ADB9=>RdAddress(6), ADB8=>RdAddress(5), 
            ADB7=>RdAddress(4), ADB6=>RdAddress(3), ADB5=>RdAddress(2), 
            ADB4=>RdAddress(1), ADB3=>RdAddress(0), ADB2=>scuba_vlo, 
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn, 
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>RdAddress(11), CSB0=>RdAddress(10), 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>mdout1_0_7, DOB6=>mdout1_0_6, 
            DOB5=>mdout1_0_5, DOB4=>mdout1_0_4, DOB3=>mdout1_0_3_2, 
            DOB2=>mdout1_0_2_2, DOB1=>mdout1_0_1_2, DOB0=>mdout1_0_0_2);

    FF_1: FD1P3DX
        port map (D=>RdAddress(10), SP=>RdClockEn, CK=>RdClock, 
            CD=>scuba_vlo, Q=>raddr10_ff);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    FF_0: FD1P3DX
        port map (D=>RdAddress(11), SP=>RdClockEn, CK=>RdClock, 
            CD=>scuba_vlo, Q=>raddr11_ff);

    mux_7: MUX21
        port map (D0=>mdout1_0_0, D1=>mdout1_0_0_2, SD=>raddr11_ff, 
            Z=>Q(0));

    mux_6: MUX21
        port map (D0=>mdout1_0_1, D1=>mdout1_0_1_2, SD=>raddr11_ff, 
            Z=>Q(1));

    mux_5: MUX21
        port map (D0=>mdout1_0_2, D1=>mdout1_0_2_2, SD=>raddr11_ff, 
            Z=>Q(2));

    mux_4: MUX21
        port map (D0=>mdout1_0_3, D1=>mdout1_0_3_2, SD=>raddr11_ff, 
            Z=>Q(3));

    mux_3: MUX21
        port map (D0=>mdout1_0_0_1, D1=>mdout1_0_4, SD=>raddr11_ff, 
            Z=>Q(4));

    mux_2: MUX21
        port map (D0=>mdout1_0_1_1, D1=>mdout1_0_5, SD=>raddr11_ff, 
            Z=>Q(5));

    mux_1: MUX21
        port map (D0=>mdout1_0_2_1, D1=>mdout1_0_6, SD=>raddr11_ff, 
            Z=>Q(6));

    mux_0: MUX21
        port map (D0=>mdout1_0_3_1, D1=>mdout1_0_7, SD=>raddr11_ff, 
            Z=>Q(7));

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of ROM is
    for Structure
        for all:FD1P3DX use entity MACHXO2.FD1P3DX(V); end for;
        for all:MUX21 use entity MACHXO2.MUX21(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:DP8KC use entity MACHXO2.DP8KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
